"""Helpers to create an OpenAI client routed through Portkey and to
produce Portkey tracing headers.

This module provides two helpers requested by the project bootstrap:
- `get_portkey_openai_client()` — returns a small helper object that
  points an OpenAI client at the Portkey gateway and includes Portkey
  tracing headers when making requests.
- `get_portkey_headers(metadata: dict)` — returns headers generated by
  Portkey's `createHeaders()` helper for tracing/experiments.

Note: The implementation tries to import `portkey-ai` (or `portkey`) and
falls back with a helpful error if the package is absent.
"""
from typing import Dict, Any, Optional
import os
try:
    from dotenv import load_dotenv

    # Load environment variables from .env in the project root if present.
    load_dotenv()
except Exception:
    # python-dotenv not installed in this environment — skip loading.
    pass

# Prefer the native Portkey client if available.
_PortkeyClass = None
try:
    from portkey_ai import Portkey as _PortkeyClass  # type: ignore
except Exception:
    _PortkeyClass = None

# Fallback: some older installs expose a module-level createHeaders helper.
_module_create_headers = None
try:
    import portkey_ai as _pk_mod  # type: ignore
    _module_create_headers = getattr(_pk_mod, "createHeaders", None)
except Exception:
    _module_create_headers = None

# Defer importing `openai` to runtime so importing this module doesn't
# fail in environments where `openai` isn't installed yet.

MODEL_NAME = os.getenv("MODEL_NAME") or os.getenv("LLM_MODEL_NAME") or "gpt-4o-mini"


def _ensure_env(name: str) -> str:
    val = os.getenv(name)
    if not val:
        raise RuntimeError(f"Environment variable {name} is required but not set. See .env.example")
    return val


def get_portkey_headers(metadata: Dict[str, Any]) -> Dict[str, str]:
    """Return Portkey tracing headers using `createHeaders()`.

    Args:
        metadata: Arbitrary metadata to attach to headers (e.g. experiment id,
                  question id, run id).

    Returns:
        A dict of HTTP headers created by Portkey's helper.
    """
    # Prefer the native Portkey client API if available.
    # Read variables from the project's .env (as provided)
    portkey_key = os.getenv("PORTKEY_API_KEY")
    gateway = os.getenv("PORTKEY_GATEWAY_URL")
    custom_bearer = os.getenv("CUSTOM_BEARER_TOKEN")
    llm_model = os.getenv("LLM_MODEL_NAME")
    provider = os.getenv("X-PORTKEY_PROVIDER")

    if _PortkeyClass is not None:
        client = _PortkeyClass(base_url=gateway, api_key=portkey_key)
        # try a couple of possible method names
        for fn in ("create_headers", "createHeaders", "createHeadersForRequest"):
            f = getattr(client, fn, None)
            if callable(f):
                headers = f(metadata)
                # attach optional project-specific headers
                if custom_bearer:
                    headers.setdefault("Authorization", f"Bearer {custom_bearer}")
                if provider:
                    headers.setdefault("X-PORTKEY-PROVIDER", provider)
                if llm_model:
                    headers.setdefault("X-PORTKEY-LLM", llm_model)
                return headers
        raise RuntimeError("Portkey client available but no header-creation method found on it.")

    # Fallback to module-level helper if present
    if _module_create_headers is not None:
        if not portkey_key:
            raise RuntimeError("PORTKEY_API_KEY is required for createHeaders fallback.")
        headers = _module_create_headers(portkey_key, metadata)
        if custom_bearer:
            headers.setdefault("Authorization", f"Bearer {custom_bearer}")
        if provider:
            headers.setdefault("X-PORTKEY-PROVIDER", provider)
        if llm_model:
            headers.setdefault("X-PORTKEY-LLM", llm_model)
        return headers

    raise RuntimeError("Missing `portkey-ai` package. Install 'portkey-ai' to use Portkey features.")


class PortkeyOpenAIClient:
    """Minimal wrapper that points OpenAI at a Portkey gateway and
    exposes a convenience method to call ChatCompletion while injecting
    Portkey headers.
    """

    def __init__(self, gateway: Optional[str], headers: Dict[str, str]):
        self._gateway = gateway or os.getenv("PORTKEY_GATEWAY_URL", "https://gateway.portkey.ai/v1")
        self._headers = headers
        # Defer openai import and configure the client when needed. We store
        # the API key now to apply when the runtime import succeeds.
        self._openai_api_key = os.getenv("OPENAI_API_KEY")

    def chat_completion(self, **kwargs):
        """Call `openai.ChatCompletion.create(...)` against the Portkey gateway.

        This method temporarily sets `openai.api_base` to the Portkey gateway
        and injects the Portkey headers into the request.
        """
        try:
            import openai  # type: ignore
        except Exception:
            raise RuntimeError("The `openai` package is required for chat calls. Install `openai`.")

        # If an API key was provided via env, set it on the imported client.
        if self._openai_api_key:
            try:
                openai.api_key = self._openai_api_key
            except Exception:
                pass
        # Merge provided headers with Portkey headers
        user_headers = kwargs.pop("headers", {}) or {}
        merged_headers = {**self._headers, **user_headers}

        # If a default model is specified in env, apply it when not provided.
        if "model" not in kwargs:
            env_model = os.getenv("LLM_MODEL_NAME")
            if env_model:
                kwargs.setdefault("model", env_model)

        prev_base = getattr(openai, "api_base", None)
        openai.api_base = self._gateway
        try:
            return openai.ChatCompletion.create(headers=merged_headers, **kwargs)
        finally:
            # restore previous state
            if prev_base is None:
                try:
                    delattr(openai, "api_base")
                except Exception:
                    pass
            else:
                openai.api_base = prev_base


def get_portkey_client():
    """Return the native Portkey client configured from the project's env."""
    if _PortkeyClass is None:
        raise RuntimeError("Missing `portkey-ai` package. Install 'portkey-ai' to use Portkey features.")
    gateway = os.getenv("PORTKEY_GATEWAY_URL") or "https://portkeygateway.perficient.com/v1"
    api_key = _ensure_env("PORTKEY_API_KEY")
    return _PortkeyClass(base_url=gateway, api_key=api_key)


def get_portkey_openai_client() -> PortkeyOpenAIClient:
    """Create and return a `PortkeyOpenAIClient`.

    The returned client will route requests through the Portkey gateway and
    include Portkey tracing headers produced by `get_portkey_headers()`.
    """
    headers = get_portkey_headers({})
    gateway = os.getenv("PORTKEY_GATEWAY_URL") or "https://portkeygateway.perficient.com/v1"
    client = PortkeyOpenAIClient(gateway=gateway, headers=headers)
    # attach a native Portkey client instance if available for downstream usage
    if _PortkeyClass is not None:
        portkey_key = os.getenv("PORTKEY_API_KEY")
        setattr(client, "portkey_client", _PortkeyClass(base_url=gateway, api_key=portkey_key))
    return client
